forge "http://forge.puppetlabs.com"

mod 'gentoo/portage'
mod 'puppet/archive'
mod 'puppet/hiera'
mod 'puppet/extlib'
mod 'puppet/make'
mod 'puppet/puppetboard'
mod 'puppet/python'
mod 'puppet/r10k'
mod 'puppet/yum'
mod 'puppetlabs/activemq'
mod 'puppetlabs/apache'
mod 'puppetlabs/apt'
mod 'puppetlabs/concat'
mod 'puppetlabs/firewall'
mod 'puppetlabs/gcc'
mod 'puppetlabs/git'
mod 'puppetlabs/inifile'
mod 'puppetlabs/java'
mod 'puppetlabs/java_ks'
mod 'puppetlabs/mysql'
mod 'puppetlabs/ntp'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/puppetdb'
mod 'puppetlabs/ruby'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/translate'
mod 'puppetlabs/vcsrepo'
mod 'stahnma/epel'
#
# Home grown modules
mod 'ten-role',
    :git => 'git@github.com:ten-peb/puppet-module-role.git'
